[project]
name = "similarity"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "openslide-python>=1.4.2",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "pyvips",
    "ray[data]>=2.48.0",
    "torchvision>=0.22.1",
    "transformers>=4.53.0",
    "fairscale",
    "timm",
    "torch==2.8.0",
    "flash-attn @ https://github.com/MiroPsota/torch_packages_builder/releases/download/flash_attn-2.8.3/flash_attn-2.8.3%2Bpt2.8.0cu129-cp312-cp312-linux_x86_64.whl",
    "gigapath @ git+https://github.com/jiribuchta/prov-gigapath.git@main",
]

[tool.setuptools.packages.find]
where = ["src"]
