job:
  job_name: "gigapath"
  username: "jiribuchta"
  cpu: 8
  shm: "128Gi"
  memory: "128Gi"
  gpu: "H100"
  public: False
  storage:
    mou: True

slide:
  slide_path: "/mnt/data/MOU/breast/comparison_of_scanners/FLASH2021_6802-01-T.mrxs"
  save_path: "/mnt/projects/ri_scale/privagams/tests"
  overwrite: False

workers:
  batch_size: 512
  workers: 0